---
- name: install php 54
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ius_prefix }}php54-common-5.4.45-1.ius.{{ ius_distribution }}.x86_64.rpm"
    - "{{ ius_prefix }}php54-cli-5.4.45-1.ius.{{ ius_distribution }}.x86_64.rpm"
    - "{{ ius_prefix }}php54-5.4.45-1.ius.{{ ius_distribution }}.x86_64.rpm"
...