---
- name: install remi repository
  package:
    name: https://rpms.remirepo.net/enterprise/remi-release-6.rpm
    state: present

- name: install php 5.4 with remi
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php54
    - php54-php
    - php54-php-common
    - php54-php-cli

- name: symlink php config
  file:
    src: "{{ php.config_root }}/etc/php.ini"
    dest: /etc/php.ini
    state: link

- name: symlink php config directory
  file:
    src: "{{ php.config_root }}/etc/php.d"
    dest: /etc/php.d
    state: link

- name: install php 5.4 modules with remi
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php54-php-mcrypt
    - php54-php-bcmath
    - php54-php-xml
    - php54-php-gd
    - php54-php-mbstring
    - php54-php-pdo
    - php54-php-tidy
    - php54-php-pecl-geoip
    - php54-php-pecl-apc
    - php54-php-pecl-ssh2
    - php54-php-mysqlnd
    - php54-php-pecl-zip
...